### ISSUE TITLE
CQ-editor error when trying to export build123d objects

### ISSUE THREAD

**Issue by jdegenstein** [jdegenstein/jmwright-CQ-Editor#4]
CQ-editor will export foo.part.wrapped but not foo.part nor foo. The error for the CQ-editor log is:
```
[18:18:07.994772] ERROR: Uncaught exception occurred
Traceback (most recent call last):
  File "cq_editor\widgets\object_tree.py", line 139, in <lambda>
  File "cq_editor\widgets\object_tree.py", line 337, in export
  File "cq_editor\cq_utils.py", line 92, in export
  File "cq_editor\cq_utils.py", line 50, in to_compound
ValueError: Invalid type <class 'list'>
```

See https://github.com/gumyr/build123d/issues/54 for a possible fix

**Comment by jdegenstein** [comment]
This should now be fixed by https://github.com/jdegenstein/jmwright-CQ-Editor/commit/a144b2e60a71f816abbf667443186a54faefcc98
